name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install coreutils (for shuf command)
      run: sudo apt-get install coreutils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Analysing the code with autopep8
      run: |
        autopep8 --in-place --recursive hw2_debugging.py rand.py

    - name: Analysing the code with pylint
      run: |
        pylint hw2_debugging.py rand.py
        
    - name: Analysing the code with flake8
      run: |
        flake8 hw2_debugging.py rand.py
    
    - name: Analysing the code with radon
      run: |
        radon cc hw2_debugging.py rand.py

    - name: test cases coverage
      run: |
        pytest -v tests/
      uses: we-cli/coverage-badge-action@main

    # - name: Code coverage and test cases coverage
    #   run: |
    #     pytest --cov=. --cov-report=term --cov-report=json:./coverage/coverage-summary.json


    # - name: Update Coverage Badge
    #   if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    #   uses: we-cli/coverage-badge-action@main