name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install coreutils (for shuf command)
      run: sudo apt-get install coreutils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install codecov
    
    - name: Analysing the code with autopep8
      run: |
        autopep8 --in-place --recursive hw2_debugging.py rand.py

    - name: Analysing the code with pylint
      run: |
        pylint hw2_debugging.py rand.py
        
    - name: Analysing the code with flake8
      run: |
        flake8 hw2_debugging.py rand.py
    
    - name: Analysing the code with radon
      run: |
        radon cc hw2_debugging.py rand.py

    - name: Run test cases
      run: |
        pytest -v tests/

    - name: Run tests and collect coverage
      run: |
        pytest --cov=your_module_name --cov-report=xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

   

    # - name: Generate coverage badge
    #   uses: we-cli/coverage-badge-action@main
