name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.1
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.1"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    
    - name: Code coverage and test cases coverage
      run: |
        pytest --cov=. --cov-report=term --cov-report=json:coverage.json

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
          token: ${{secrets.CODE_COV_TOKEN }}
          files: ./coverage.json
